times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'Chapecoense','Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')
print('=-' * 20)
print(f'Os 5 primeiros colocados são {times[0:5]}')
print('=-' * 20)
print(f'Os últimos 4 colocados são {times[-4:]}')
print('=-' * 20)
print(f'A lista com os nomes em ordem alfabética é {sorted(times)}')
print('=-' * 20)
print(f'O time Chapecoense está na posição {times.index("Chapecoense")+1} da tabela')